# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7506cf847c65fe62bb4597bdb690394f84413eee6e57611676ef1c5df36ff4c65cf7d910c096028acdf80830a14247cb0c5be5f6e398e0406b40d955aa6f97ff

test:
  secret_key_base: 755aeb3901a6a24f913f4b8a4641b89dc5a6e6e93a4c2768a04869ce1b3c5783bd9e1887e676d2d2ad86021dbd9367c3e29a6595eeee1254570743d32a5335ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
